spring:
  freemarker:
    charset: UTF-8
    content-type: text/html
    expose-session-attributes: true

  #thymelaef配置
  thymeleaf:
    #关闭缓存
    cache: false
    mode: LEGACYHTML5
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&severTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间,默认600000(10分钟)
      idle-timeout: 18000
      #最大连接数,默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间 0表示永久存活, 默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间 默认30000 30秒
      connection-timeout: 30000
      connection-test-query: SELECT 1

# mybatis-plus 配置
mybatis-plus:
  # 配置mapper映射文件
  mapper-location: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名(默认是类名)
  tyep-aliases-package: edu.hb.taosijie.redisshopping.pojo

# MyBatis SQL打印(方法接口所在的包,不是mapper.xml所在的包)
logging:
  charset:
    console: utf-8
  level:
    edu.hb.taosijie.redisshopping: debug

server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8